controller_list:
  - name: fake_spherical_controller
    type: $(arg fake_execution_type)
    joints:
      - base_Revolute_1
      - large_Revolute_2
      - medium_Revolute_3
initial:  # Define initial robot poses per group
  - group: spherical
    pose: home