spherical_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_Revolute_1
    - large_Revolute_2
    - medium_Revolute_3
  gains:
    base_Revolute_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    large_Revolute_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    medium_Revolute_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1